In [10]:
# 创建数组
import numpy as np

matrix = np.array([1, 2, 3, 4, 5])  # 创建一维数组
print(matrix.shape)  # 数组形状：(5,)
# 创建二维数组
matrix = np.array([[2, 1, 2], [-4, 3, 1], [2, 3, 5]])
print(matrix.shape)  # 数组形状：(3, 3)
# 创建三维数组
matrix = np.array([[[2, 1, 2], [-4, 3, 1], [2, 3, 5]], [[2, 1, 2], [-4, 3, 1], [2, 3, 5]], [[2, 1, 2], [-4, 3, 1], [2, 3, 5]]])
print(matrix.shape)  # 输出：(3, 3, 3)

(5,)
(3, 3)
(3, 3, 3)


In [11]:
# 计算行列式
import numpy as np

matrix = np.array([[2, 1, 2], [-4, 3, 1], [2, 3, 5]])
det = np.linalg.det(matrix)
print("行列式值:", det)

行列式值: 10.000000000000002


In [ ]:
# 求解线性方程组
import numpy as np

A = np.array([[3, 2], [1, -1]])  # 系数矩阵
b = np.array([7, -1])  # 常数项
x = np.linalg.solve(A, b)  # 求解
print(x)  # 输出：[1. 2.]

[1. 2.]


In [ ]:
# 方阵的特征值/向量
import numpy as np

A = np.array([[4, 1], [2, 3]])  # 输入矩阵（必须为方阵）
print(np.linalg.eig(A))  # 输出特征值/向量


EigResult(eigenvalues=array([5., 2.]), eigenvectors=array([[ 0.70710678, -0.4472136 ],
       [ 0.70710678,  0.89442719]]))


In [ ]:
# 方阵的特征值/向量
import numpy as np

A = np.array([[4, 1], [2, 3]])  # 输入矩阵（必须为方阵）
eigenvalues, eigenvectors = np.linalg.eig(A)  # 解算特征值/向量
print("特征值:", eigenvalues)  # 输出：[5. 2.]
print("特征向量:\n", eigenvectors)
# 输出：
# [[ 0.70710678 -0.4472136 ]
#  [ 0.70710678  0.89442719]]

特征值: [5. 2.]
特征向量:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [ ]:
# 计算行列式
import numpy as np

# 创建一维数组
matrix = np.array([1, 2, 3, 4, 5])
# 创建n维数组
matrix = np.array([[2, 1, 2], [-4, 3, 1], [2, 3, 5]])
det = np.linalg.det(matrix)
print("行列式值:", det)

行列式值: 10.000000000000002


In [ ]:
import numpy as np

print(np.arange(5))  # [0 1 2 3 4]
print(np.arange(2, 5))  # [2 3 4]
print(np.arange(0, 1, 0.2))  # [0.  0.2 0.4 0.6 0.8]
print(np.arange(-2, 2))  # [-2 -1  0  1]

[0 1 2 3 4]
[2 3 4]
[0.  0.2 0.4 0.6 0.8]
[-2 -1  0  1]


In [ ]:
# 创建0到1的5个等间隔值
print(np.linspace(0, 1, 5))  # [0.  0.25 0.5  0.75 1. ]

# 不包含终止值
arr = np.linspace(0, 10, 5, endpoint=False)
# 输出：[0. 2. 4. 6. 8.]

# 返回步长
samples, step = np.linspace(0, 10, 11, retstep=True)
# step值为1.0


[0.   0.25 0.5  0.75 1.  ]


In [7]:
import numpy as np

arr = np.array([[2.73351472, 0.47539713, 3.63280356, 1.4787706, 3.13661701], [1.40305914, 2.27134829, 2.73437132, 1.88939679, 0.0384238], [1.56666697, -0.40088431, 0.54893762, 3.3776724, 2.27490386]])
print(arr)

[[ 2.73351472  0.47539713  3.63280356  1.4787706   3.13661701]
 [ 1.40305914  2.27134829  2.73437132  1.88939679  0.0384238 ]
 [ 1.56666697 -0.40088431  0.54893762  3.3776724   2.27490386]]
