In [29]:
import numpy as np

l = [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 1, 2, 3, 4, 5, 6, 7, 8, 9], [3, 1, 2, 3, 4, 5, 6, 7, 8, 9], [4, 1, 2, 3, 4, 5, 6, 7, 8, 9], [5, 1, 2, 3, 4, 5, 6, 7, 8, 9], [6, 1, 2, 3, 4, 5, 6, 7, 8, 9],
     [7, 1, 2, 3, 4, 5, 6, 7, 8, 9], [8, 1, 2, 3, 4, 5, 6, 7, 8, 9], [9, 1, 2, 3, 4, 5, 6, 7, 8, 9]]
arr = np.array(l)
print(arr[:, :7:2])

[[0 2 4 6]
 [1 2 4 6]
 [2 2 4 6]
 [3 2 4 6]
 [4 2 4 6]
 [5 2 4 6]
 [6 2 4 6]
 [7 2 4 6]
 [8 2 4 6]
 [9 2 4 6]]


In [30]:
# 返回满足条件的数
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
result = arr[arr > 3]  
print(result) # 输出 [4 5 6]

[4 5 6]


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
result = arr[(arr % 2 == 0) | (arr % 3 == 0)]
print(result) # 输出 [2 3 4 6]

[2 3 4 6]


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
result = arr[arr % 2 == 0]
print(result) # 输出 [2 3 4 6]

[2 4 6]
