In [1]:
# 统计描述
import numpy as np

a = np.array([2, 12, 11, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.sort(a))
print(a.max())  # 最大值
print(a.min())  # 最小值
print(a.sum())  # 求和
print(a.mean())  # 平均值
print(a.std())  # 方差
print(a.var())  # 标准差

[ 2  3  4  5  6  7  8  9 10 11 12]
12
2
77
7.0
3.1622776601683795
10.0


数据生成完成！


前三行：
     考号   姓名  班级     语文     数学     英语     总分   班名次
0  1000  任桂香  一班   88.0  105.0   60.0  253.0  37.0
1  1001  陈桂芳  二班   77.0   88.0  133.0  298.0   9.0
2  1002  陈淑华  一班  118.0   86.0  105.0  309.0   5.0

后两行：
      考号   姓名  班级    语文    数学     英语     总分   班名次
98  1098  莫秀兰  一班  75.0  99.0  103.0  277.0  22.0
99  1099   温杰  二班  50.0  64.0   73.0  187.0  50.0


In [ ]:
from numpy import *

L = [[2.73351472, 0.47539713, 3.63280356, 1.4787706, 3.13661701], [1.40305914, 2.27134829, 2.73437132, 1.88939679, 0.0384238], [1.56666697, -0.40088431, 0.54893762, 3.3776724, 2.27490386]]

#将列表转化为数组
arrL = array(L)

## 获取arr1,...arr5
arr1 = arrL[:, 1:2]

arr2 = arrL[1:, [2, 3, 4]]
arr22 = arrL[1:, 2:]

arr3 = arrL[[0, 0, 2, 2], [1, 3, 1, 3]]
arr33 = arrL[::2, [1, 3]]
arr4 = arrL[(arrL >= 2.5) & (arrL <= 3.5)]  ##(arrL[where((arrL>=2.5) & (arrL<=3.5))])
arr5 = arrL[where((arrL < 0) | (arrL > 3))]

print("arr1=", arr1)
print("arr2=", arr2)
print("arr22=", arr22)
print("arr3=", arr3)
print("arr33=", arr33)
print("arr4=", arr4)
print("arr5=", arr5)

arr1= [[ 0.47539713]
 [ 2.27134829]
 [-0.40088431]]
arr2= [[2.73437132 1.88939679 0.0384238 ]
 [0.54893762 3.3776724  2.27490386]]
arr22= [[2.73437132 1.88939679 0.0384238 ]
 [0.54893762 3.3776724  2.27490386]]
arr3= [ 0.47539713  1.4787706  -0.40088431  3.3776724 ]
arr33= [[ 0.47539713  1.4787706 ]
 [-0.40088431  3.3776724 ]]
arr4= [2.73351472 3.13661701 2.73437132 3.3776724 ]
arr5= [ 3.63280356  3.13661701 -0.40088431  3.3776724 ]


[4 5 6]
